from .qa_map_reduce_prompt  import COMBINE_PROMPT, EXAMPLE_PROMPT,QUESTION_PROMPT
from .qa_refine_prompt import DEFAULT_REFINE_PROMPT, DEFAULT_TEXT_QA_PROMPT, EXAMPLE_PROMPT
from .kb_select_prompt import KB_SELECT_PROMPT, KB_SELECT_PROMPT_TMPL
from .condense_quest_prompt import CONDENSE_QUESTION_PROMPT_ZH
from .query_collection_name import query_collection_name
from .my_vectordb import My_VectorStore